name = "vid-orders"
main = "src/index.js"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VAULT_TOKEN_CACHE"
id = "ff476d78fe804fba902ee57404e56070"

[observability]
enabled = true
